version: '3.8'

services:
  db:
    image: postgres:15
    container_name: chat-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-network

  redis:
    image: redis:latest
    container_name: chat-redis
    networks:
      - chat-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-app
    environment:
      DATABASE_URL: postgres://user:password@db:5432/chatdb
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your_jwt_secret
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  postgres_data:
